### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by Kostanos** [todda00/meteor-collection-revisions#4]
Any Idea on this error?
It is a fresh install, and I'm simple adding revisions to collections.
The same code is working well on my another application.

```
 .meteor/packages/meteor-tool/.1.1.10.1mpkebu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
            throw(ex);
                  ^
 ReferenceError: _ is not defined
     at [object Object].Mongo.Collection.attachCollectionRevisions (packages/todda00_collection-revisions/packages/todda00_collection-revisions.js:36:1)
     at Herald.addCourier.media.onsite (lib/collections/dd_orders.js:3:20)
     at .meteor/local/build/programs/server/packages/deliverycommon.js:752:4
     at server/fixtures.js:6:59
     at .meteor/local/build/programs/server/boot.js:242:10
     at Array.forEach (native)
     at Function._.each._.forEach (.meteor/packages/meteor-tool/.1.1.10.1mpkebu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at .meteor/local/build/programs/server/boot.js:137:5
```

PS. underscore is added on main application, and I see it is a dependency on collection-revisions package

**Comment by Kostanos** [comment]
Somehow I got compiled this in one app, but adding the package in another app, got the same error.
